loki:
  enabled: true
  persistence:
    enabled: true
      #storageClassName: standard
    size: 5Gi
  config:
    server:
      http_listen_port: 3100

promtail:
  enabled: true
  config:
    # -- The config of clients of the Promtail server
    # Must be reference in `config.file` to configure `clients`
    # @default -- See `values.yaml`
    server:
      log_leve: debug
      http_listen_port: 3101
        #clients:
        #  - url: http://loki-stack-internal-lb:3100/loki/api/v1/push
        #lokiAddress: http://loki-stack-internal-lb:3100/loki/api/v1/push
      #  - url: http://10.132.0.57:3100/loki/api/v1/push
      #lokiAddress: http://10.132.0.57:3100/loki/api/v1/push
        #- url: http://loki-stack:3100/loki/api/v1/push
    lokiAddress: http://loki-stack:3100/loki/api/v1/push
    scrapeConfigs: |
      # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
      - job_name: kubernetes-pods
        pipeline_stages:
          {{- toYaml .Values.config.snippets.pipelineStages | nindent 4 }}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_controller_name
            regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
            action: replace
            target_label: __tmp_controller_name
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
              - __meta_kubernetes_pod_label_app
              - __tmp_controller_name
              - __meta_kubernetes_pod_name
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: app
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_instance
              - __meta_kubernetes_pod_label_release
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: instance
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_component
              - __meta_kubernetes_pod_label_component
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: component
          - replacement: kubernetes-pods
            target_label: scrape_job
          {{- end }}
          {{- toYaml .Values.config.snippets.common | nindent 4 }}
          {{- with .Values.config.snippets.extraRelabelConfigs }}
          {{- toYaml . | nindent 4 }}
          {{- end }}
      - job_name: system
        entry_parser: raw
        static_configs:
          - targets:
              - localhost
            labels:
              job: my-app
              my-label: awesome
              __path__: /home/pikto/creator.log
    #enabled: true
    #clients:
    #- url: http://34.78.123.91:3100/loki/api/v1/push

    #fluent-bit:
    #enabled: false

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 8.3.5

prometheus:
  enabled: true

    #filebeat:
    #  #enabled: false
    #  enabled: true 
    #  filebeatConfig:
    #    filebeat.yml: |
    #      # logging.level: debug
    #      filebeat.inputs:
    #      - type: container
    #        paths:
    #          - /var/log/containers/*.log
    #        processors:
    #        - add_kubernetes_metadata:
    #            host: ${NODE_NAME}
    #            matchers:
    #            - logs_path:
    #                logs_path: "/var/log/containers/"
    #      output.logstash:
    #        hosts: ["loki-stack:3100"]
          # hosts: ["35.195.250.58:3100"]
          #hosts: ["logstash-loki:5044"]

    #logstash:
    #  enabled: false
    #  image: grafana/logstash-output-loki
    #  imageTag: 1.0.1
    #  filters:
    #    main: |-
    #      filter {
    #        if [kubernetes] {
    #          mutate {
    #            add_field => {
    #              "container_name" => "%{[kubernetes][container][name]}"
    #              "namespace" => "%{[kubernetes][namespace]}"
    #              "pod" => "%{[kubernetes][pod][name]}"
    #            }
    #            replace => { "host" => "%{[kubernetes][node][name]}"}
    #          }
    #        }
    #        mutate {
    #          remove_field => ["tags"]
    #        }
    #      }
    #  outputs:
    #    main: |-
    #      output {
    #        loki {
    #          url => "http://loki:3100/loki/api/v1/push"
    #          #username => "test"
    #          #password => "test"
    #        }
    #        # stdout { codec => rubydebug }
    #      }
    #
