apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: postgresql
  labels:
    app: postgres
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: postgresql
  labels:
    app: postgres
spec:
  storageClassName: hostpath
  #capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  namespace: postgresql
  labels:
    app: postgres
data:
  POSTGRES_DB: POSTGRESQL
  POSTGRES_USER: POSTGRESQL
  POSTGRES_PASSWORD: POSTGRESQL
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgresql
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.2
          envFrom:
            - configMapRef:
                name: postgres-configuration
          resources:
            limits:
              cpu: 250m
              memory: 200Mi
            requests:
              cpu: 150m
              memory: 150Mi
          ports:
            - containerPort: 5432
              name: postgresdb
          volumeMounts:
            - name: pv-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgresql
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres
