apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

helmCharts:
- name: promtail
  releaseName: promtail
  repo: https://grafana.github.io/helm-charts
  version: "6.9.3"
  valuesInline:
    config:
      # https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
      clients:
        - url: http://loki-headless:3100/loki/api/v1/push
