apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: graylog
  labels:
    service: elasticsearch
spec:
  replicas: 1
  selector:
   matchLabels:
    service: elasticsearch
  strategy: {}
  template:
    metadata:
      labels:
        service: elasticsearch
    spec:
      containers:
      - args:
        - elasticsearch
        - -Des.cluster.name=graylog
        image: elasticsearch:2
        name: elasticsearch
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 500m
            memory: 1500Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: elasticsearch
  name: elasticsearch
  namespace: graylog
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: elasticsearch