apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      service: graylog
  template:
    metadata:
      labels:
        service: graylog
    spec:
      containers:
        - env:
            - name: GRAYLOG_WEB_ENDPOINT_URI
              value: http://127.0.0.1:9000/api
            - name: GRAYLOG_PASSWORD_SECRET
              value: somesaltpassword
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: 5D5E792708BFA15F0AB42E817B4E69379777D2722E0529DFB031C0B847DB137D
          image: graylog/graylog:2.5.2-1
          name: graylog
          ports:
            - containerPort: 9000
            - containerPort: 12201
          resources:
            limits:
              cpu: 1000m
              memory: 1500Mi
            requests:
              cpu: 500m
              memory: 750Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: graylog
  labels:
    service: graylog
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "12201"
      port: 12201
      targetPort: 12201
  selector:
    service: graylog
---
apiVersion: v1
kind: Service
metadata:
  name: graylog-nodeport
  namespace: graylog
  labels:
    service: graylog
spec:
  type: NodePort
  selector:
    service: graylog
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "12201udp"
      port: 12201
      targetPort: 12201
      protocol: UDP
    - name: "12201tcp"
      port: 12201
      targetPort: 12201
      protocol: TCP
